// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHhXANLdfB7j923_Mx-4l5nOZ6gCtvpa4',
    appId: '1:991388739840:android:0032fa99e3df4783f92be5',
    messagingSenderId: '991388739840',
    projectId: 'sachetnapp',
    databaseURL: 'https://sachetnapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sachetnapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFcfepkGMWxloBeFI9k_RGSVYo0Ep7HpU',
    appId: '1:991388739840:ios:207c4d7d23a314e1f92be5',
    messagingSenderId: '991388739840',
    projectId: 'sachetnapp',
    databaseURL: 'https://sachetnapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sachetnapp.appspot.com',
    iosBundleId: 'com.example.sachetanaFirebase',
  );
}
